spring.application.name=order-service

server.port=9010

feign.client.config.default.connectTimeout=2000
feign.client.config.default.readTimeout=2000

payment-service.url=http://payment-service:9020

resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.paymentService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.slowCallDurationThreshold=2s